title = "Stefano Penna"
baseURL = "/"
theme = "hugo-resume"
languageCode = "it-it"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

relativeURLs = true
canonifyURLs = false

defaultContentLanguage = "it"
defaultContentLanguageInSubdir = false

[params]
address = "Torino, TO"
email = "stefano@stefanopenna.it"
workemail = "s343693@studenti.polito.it"
favicon = "/favicon.ico"
firstName = "Stefano"
lastName = "Penna"
phone = "3319413120"
profileImage = "https://cdn.stefanopenna.it/images/stefano.png"
vcardURL = "https://stefanopenna.it"
showQr = false
showContact = true
showBoards  = true
showCertifications = true
showSocializations = true
# sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["education"]
vcardfields = [
    "name",
    "image",
    # "org", # I'm a student
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

# [params.google]
# 
# [params.google.analytics]
# trackerID = "XX-123446-01"

[[params.handles]]
    name = "Email"
    link = "mailto:stefano@stefanopenna.it"
    icon = "envelope"
    iconStyle = "fa-solid"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/stefano-penna/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/stefanopennaa/"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true

[markup.goldmark.renderer]
unsafe = true